name: Compliance check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  compliance:
    permissions:
      contents: read
    uses: CCTC-team/.github/.github/workflows/compliance-check.yml@main
